### PR TITLE
Rcd upgrade

### PR DESCRIPTION
**Pull request by ZioZan**
Improved RCD. 
Added advanced rcd with increased capacity and capable of constructing and deconstructing reinforced walls.

### CODE REVIEW

**Comment by Sierracode** [comment]
What a clean looking PR. can I get a summery of what this meme is so I don't have to download it to check it?

**Comment by ZioZan** [comment]
Normal RCD can now make reinforced windows. Added a new version of RCD to cargo and research, with new sprites. New version has all previous functions, 10 times bigger ammo capacity and can construct and deconstruct reinforced walls. It is pretty costly though.

**Comment by ZioZan** [comment]
Also added 2 RCD (old version) and 2 RPD to engineering vending machine (like on tg).

**Comment by Sierracode** [comment]
10 times is a little much fam thats a lot of walls. als please tell me you need high reseach to make this nigga breaking reinforced walls with a click das bad

**Comment by ZioZan** [comment]
It requires Materials level 7, Engineering level 6, Magnets level 6. This is almost highest level.
I agree that 10 times is too much. But I always wanted something to construct or deconstruct many reinforced walls at once. As with platsteel it takes pretty long and platsteel itself is kinda rare and expensive.

So how much do you want capacity to be?
Right now, we have normal RCD at 100 capacity, ammo increases by 20.
There already was admin version called combat RCD which could deconstruct reinforced walls by consuming 20 ammo, capacity 500. Maybe ERT spawned with it.

Tg has normal RCD at 160 capacity, ammo increases by 40.
Combat RCD is at 600 capacity there.

I bumped normal RCD to 200 and set my new version, Advanced RCD at 2000. That is maybe too much. I can set it to 500 or 1000 and set normal RCD back to 100 if you want.

**Comment by Sierracode** [comment]
What I would allow is having them be "high" as a maximum capacity but have them start with a low ammo in them so that people have to spend a bit more resources making ammo packs to fill it up to start.

**Comment by ZioZan** [comment]
That's how it is. Both normal and advanced RCDs start at 0 capacity. Ammo adds more capacity for additional resources. Normal rcd ammo costs just metal and glass, 5 sheets of both. Advanced RCD ammo costs 4 metal, 4 glass, 4 plasma sheets. This can be changed too, I can add additional materials like gold, silver, uranium, or diamond. I think 1000 or 500 maximum capacity for advanced RCD will be fine with ammo being 1/4 of full capacity.

**Comment by ZioZan** [comment]
I checked and I was wrong about resources. So I fixed it.
Normal RCD costs 40 metal and 20 glass sheets
Normal RCD ammo costs 8 metal and 4 glass sheets
Advanced RCD now costs 40 metal, 20 glass, 8 gold, 8 silver 8 uranium sheets.
Advanced RCD ammo now costs 8 metal, 4 glass, 4 gold, 4 silver 4 uranium sheets.
Maximum capacity of advanced RCD is now 1000.
It requires Materials level 7, Engineering level 6, Magnets level 7, the maximum possible research.

**Comment by vultraz168** [comment]
Who do you intend to use this?

**Comment by ZioZan** [comment]
This thing is most useful for engineers. I rarely see engineers use RCD. With this they can fix breaches much more easily. Last time I used RCD I used ammo way too fast. So I made version with more ammo that requires research. I know it can be used to grief, but so can be Bag of Holding which is much more cheap.

**Pull request merged**
